name: Latest Blog Posts Update
on:
  push:
    paths:
      - ".github/workflows/*"
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@domwebberr"
          feed_names: "Medium"
          template: "$newline- [$feedName: $title]($url) $newline"
          tag_post_pre_newline: true